"""
JRA-VAN mykeibadb Table Name Mapping

Defines actual table names generated by mykeibadb.
Verified and updated after data import on 2024/12/30.
"""

from typing import Final

# =============================================================================
# Table Name Definitions (mykeibadb actual table names)
# =============================================================================

# Race related
TABLE_RACE: Final[str] = "race_shosai"  # RA: Race details
TABLE_UMA_RACE: Final[str] = "umagoto_race_joho"  # SE: Per-horse race information

# Horse master
TABLE_UMA: Final[str] = "kyosoba_master2"  # UM: Racehorse master
TABLE_SANKU: Final[str] = "sanku_master2"  # SK: Offspring master (3-generation pedigree)
TABLE_HANSYOKU: Final[str] = "hanshokuba_master2"  # HN: Breeding horse master

# Training data
TABLE_HANRO_CHOKYO: Final[str] = "hanro_chokyo"  # HC: Slope training
TABLE_WOOD_CHOKYO: Final[str] = "woodchip_chokyo"  # WC: Woodchip training

# Personnel master
TABLE_KISYU: Final[str] = "kishu_master"  # KS: Jockey master
TABLE_CHOKYOSI: Final[str] = "chokyoshi_master"  # CH: Trainer master

# Statistics by entry (win/place counts)
TABLE_SHUTUBA_KEIBAJO: Final[str] = "shussobetsu_keibajo"  # By racecourse
TABLE_SHUTUBA_KYORI: Final[str] = "shussobetsu_kyori"  # By distance
TABLE_SHUTUBA_BABA: Final[str] = "shussobetsu_baba"  # By track condition
TABLE_SHUTUBA_KISHU: Final[str] = "shussobetsu_kishu"  # By jockey
TABLE_SHUTUBA_CHOKYOSI: Final[str] = "shussobetsu_chokyoshi"  # By trainer
TABLE_SHUTUBA_BANUSHI: Final[str] = "shussobetsu_banushi"  # By owner
TABLE_SHUTUBA_SEISANSHA: Final[str] = "shussobetsu_seisansha2"  # By breeder

# Payouts and odds
TABLE_HARAIMODOSI: Final[str] = "haraimodoshi"  # HR: Payouts
TABLE_ODDS_TANSHO: Final[str] = "odds1_tansho"  # O1: Win odds
TABLE_ODDS_FUKUSHO: Final[str] = "odds1_fukusho"  # O1: Place odds
TABLE_ODDS_WAKUREN: Final[str] = "odds1_wakuren"  # O1: Bracket quinella odds
TABLE_ODDS_UMAREN: Final[str] = "odds2_umaren"  # O2: Quinella odds
TABLE_ODDS_WIDE: Final[str] = "odds3_wide"  # O3: Wide odds
TABLE_ODDS_UMATAN: Final[str] = "odds4_umatan"  # O4: Exacta odds
TABLE_ODDS_SANRENPUKU: Final[str] = "odds5_sanrenpuku"  # O5: Trio odds
TABLE_ODDS_SANRENTAN: Final[str] = "odds6_sanrentan"  # O6: Trifecta odds

# Schedule and events
TABLE_KAISAI_SCHEDULE: Final[str] = "kaisai_schedule"  # Race meeting schedule
TABLE_TENKO_BABA: Final[str] = "tenko_baba_jotai"  # Weather and track condition
TABLE_HASSO_JIKOKU: Final[str] = "hassojikoku_henko"  # Post time change
TABLE_KISYU_HENKO: Final[str] = "kishu_henko"  # Jockey change
TABLE_COURSE_HENKO: Final[str] = "course_henko"  # Course change

# Master information
TABLE_KEITO_INFO: Final[str] = "keito_joho2"  # BT: Bloodline information
TABLE_COURSE_INFO: Final[str] = "course_joho"  # CS: Course information
TABLE_RECORD_MASTER: Final[str] = "record_master"  # RC: Record master
TABLE_KEIBAJO_CODE: Final[str] = "keibajo_code"  # Racecourse code

# Special registration
TABLE_TOKUBETSU_TOROKU: Final[str] = "tokubetsu_torokuba"  # TK: Special registered horses

# Other masters
TABLE_BANUSHI: Final[str] = "banushi_master"  # Owner master
TABLE_SEISANSHA: Final[str] = "seisansha_master2"  # Breeder master

# =============================================================================
# Column Name Definitions (mykeibadb actual column names)
# =============================================================================

# Primary/foreign keys
COL_RACE_ID: Final[str] = "race_code"  # Race code (16 digits)
COL_KETTONUM: Final[str] = "ketto_toroku_bango"  # Pedigree registration number
COL_UMABAN: Final[str] = "umaban"  # Horse number

# Race components
COL_KAISAI_YEAR: Final[str] = "kaisai_nen"  # Race meeting year
COL_KAISAI_MONTHDAY: Final[str] = "kaisai_gappi"  # Race meeting month/day (MMDD)
COL_JYOCD: Final[str] = "keibajo_code"  # Racecourse code
COL_KAISAI_KAI: Final[str] = "kaisai_kai"  # Meeting number
COL_KAISAI_NICHIME: Final[str] = "kaisai_nichime"  # Day of meeting
COL_RACE_NUM: Final[str] = "race_bango"  # Race number

# Data type
COL_DATA_KUBUN: Final[str] = "data_kubun"  # Data classification (7=finalized)

# Race information
COL_RACE_NAME: Final[str] = "kyosomei_hondai"  # Race name (main title)
COL_RACE_NAME_SHORT: Final[str] = "kyosomei_ryakusho_10"  # Race name (10-char abbreviation)
COL_GRADE_CD: Final[str] = "grade_code"  # Grade code
COL_TRACK_CD: Final[str] = "track_code"  # Track code
COL_KYORI: Final[str] = "kyori"  # Distance
COL_TENKO_CD: Final[str] = "tenko_code"  # Weather code
COL_SHIBA_BABA_CD: Final[str] = "shiba_babajotai_code"  # Turf track condition code
COL_DIRT_BABA_CD: Final[str] = "dirt_babajotai_code"  # Dirt track condition code
COL_HASSO_JIKOKU: Final[str] = "hasso_jikoku"  # Post time
COL_KYOSO_SHUBETSU_CD: Final[str] = "kyoso_shubetsu_code"  # Race type code

# Age-specific race condition codes (actual DB columns)
COL_KYOSO_JOKEN_2SAI: Final[str] = "kyoso_joken_code_2sai"
COL_KYOSO_JOKEN_3SAI: Final[str] = "kyoso_joken_code_3sai"
COL_KYOSO_JOKEN_4SAI: Final[str] = "kyoso_joken_code_4sai"
COL_KYOSO_JOKEN_5SAI_IJO: Final[str] = "kyoso_joken_code_5sai_ijo"

# Horse information
COL_BAMEI: Final[str] = "bamei"  # Horse name
COL_SEX: Final[str] = "seibetsu_code"  # Sex code
COL_KEIROCODE: Final[str] = "moshoku_code"  # Coat color code
COL_BIRTH_DATE: Final[str] = "seinengappi"  # Birth date

# Results
COL_KAKUTEI_CHAKUJUN: Final[str] = "kakutei_chakujun"  # Final finishing position
COL_着順: Final[str] = "kakutei_chakujun"  # Final finishing position (alias)
COL_TIME: Final[str] = "soha_time"  # Finishing time
COL_BATAIJU: Final[str] = "bataiju"  # Horse weight
COL_KINRYO: Final[str] = "futan_juryo"  # Impost weight
COL_RACE_DATE: Final[str] = "race_date"  # Race date
COL_WAKUBAN: Final[str] = "wakuban"  # Gate number
COL_BAREI: Final[str] = "barei"  # Horse age
COL_TOZAI_CODE: Final[str] = "tozai_shozoku_code"  # East/West affiliation code

# Jockey and trainer
COL_KISYUCODE: Final[str] = "kishu_code"  # Jockey code
COL_CHOKYOSICODE: Final[str] = "chokyoshi_code"  # Trainer code
COL_KISYU_NAME: Final[str] = "kishumei"  # Jockey name
COL_KISYU_NAME_SHORT: Final[str] = "kishumei_ryakusho"  # Jockey name (abbreviation)
COL_TRAINER_NAME: Final[str] = "chokyoshimei"  # Trainer name (alias)
COL_CHOKYOSI_NAME: Final[str] = "chokyoshimei"  # Trainer name
COL_CHOKYOSI_NAME_SHORT: Final[str] = "chokyoshimei_ryakusho"  # Trainer name (abbreviation)

# Pedigree
COL_SANDAI_KETTO: Final[str] = "sandai_ketto"  # 3-generation pedigree array
COL_HANSYOKU_NUM: Final[str] = "hanshoku_toroku_bango"  # Breeding registration number
COL_HANSYOKUBA_NAME: Final[str] = "hanshokubamei"  # Breeding horse name

# Training
COL_CHOKYO_DATE: Final[str] = "chokyo_nengappi"  # Training date
COL_TIME_4F: Final[str] = "time_4f"  # 4-furlong time
COL_TIME_3F: Final[str] = "time_3f"  # 3-furlong time

# =============================================================================
# Data Classification Constants
# =============================================================================

DATA_KUBUN_KAKUTEI: Final[str] = "7"  # Finalized data
DATA_KUBUN_SOKUHO: Final[str] = "0"  # Preliminary data

# =============================================================================
# Grade Code Constants
# =============================================================================

GRADE_G1: Final[str] = "A"
GRADE_G2: Final[str] = "B"
GRADE_G3: Final[str] = "C"
GRADE_LISTED: Final[str] = "D"
GRADE_OPEN: Final[str] = "E"
GRADE_1600_BAN: Final[str] = "F"
GRADE_1000_BAN: Final[str] = "G"
GRADE_500_BAN: Final[str] = "H"
GRADE_UNDER_500: Final[str] = "I"
GRADE_SHINSHIN: Final[str] = "J"

# =============================================================================
# Utility Functions
# =============================================================================


def get_all_table_names() -> dict[str, str]:
    """Return mapping of all table names (logical name -> physical name)."""
    return {
        "race": TABLE_RACE,
        "uma_race": TABLE_UMA_RACE,
        "uma": TABLE_UMA,
        "sanku": TABLE_SANKU,
        "hansyoku": TABLE_HANSYOKU,
        "hanro_chokyo": TABLE_HANRO_CHOKYO,
        "wood_chokyo": TABLE_WOOD_CHOKYO,
        "kisyu": TABLE_KISYU,
        "chokyosi": TABLE_CHOKYOSI,
        "shutuba_keibajo": TABLE_SHUTUBA_KEIBAJO,
        "shutuba_kyori": TABLE_SHUTUBA_KYORI,
        "shutuba_baba": TABLE_SHUTUBA_BABA,
        "shutuba_kishu": TABLE_SHUTUBA_KISHU,
        "shutuba_chokyosi": TABLE_SHUTUBA_CHOKYOSI,
        "shutuba_banushi": TABLE_SHUTUBA_BANUSHI,
        "shutuba_seisansha": TABLE_SHUTUBA_SEISANSHA,
        "haraimodosi": TABLE_HARAIMODOSI,
        "odds_tansho": TABLE_ODDS_TANSHO,
        "odds_fukusho": TABLE_ODDS_FUKUSHO,
        "odds_wakuren": TABLE_ODDS_WAKUREN,
        "odds_umaren": TABLE_ODDS_UMAREN,
        "odds_wide": TABLE_ODDS_WIDE,
        "odds_umatan": TABLE_ODDS_UMATAN,
        "odds_sanrenpuku": TABLE_ODDS_SANRENPUKU,
        "odds_sanrentan": TABLE_ODDS_SANRENTAN,
        "kaisai_schedule": TABLE_KAISAI_SCHEDULE,
        "tenko_baba": TABLE_TENKO_BABA,
        "hasso_jikoku": TABLE_HASSO_JIKOKU,
        "kisyu_henko": TABLE_KISYU_HENKO,
        "course_henko": TABLE_COURSE_HENKO,
        "keito_info": TABLE_KEITO_INFO,
        "course_info": TABLE_COURSE_INFO,
        "record_master": TABLE_RECORD_MASTER,
        "keibajo_code": TABLE_KEIBAJO_CODE,
        "tokubetsu_toroku": TABLE_TOKUBETSU_TOROKU,
        "banushi": TABLE_BANUSHI,
        "seisansha": TABLE_SEISANSHA,
    }


def verify_table_names_sql() -> str:
    """
    Generate SQL to verify actual table names.

    Returns:
        SQL statement executable in PostgreSQL to list all tables
    """
    return """
-- Display all tables in the current database
SELECT
    schemaname,
    tablename,
    pg_size_pretty(pg_total_relation_size(schemaname||'.'||tablename)) AS size
FROM pg_tables
WHERE schemaname = 'public'
ORDER BY tablename;
    """
